version: "3.7"
services:
  discovery-service:
    build:
      dockerfile: Dockerfile
      context: ./service-registry
    image: discovery-service:latest
    restart: on-failure
    ports:
      - 8761:8761
  gateway-service:
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    image: gateway-service:latest
    restart: on-failure
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
    ports:
      - 80:8000
  ui-service:
    build:
      dockerfile: Dockerfile
      context: ./ui
    image: ui-service:latest
    restart: on-failure
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
    ports:
      - 8082:8082
  darkmode-service:
    build:
      dockerfile: Dockerfile
      context: ./dark-mode
    image: darkmode-service:latest
    restart: on-failure
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
    ports:
      - 8083:8083
  compiler-service:
    build:
      dockerfile: Dockerfile
      context: ./compiler
    image: compiler-service:latest
    restart: on-failure
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
    ports:
      - 8081:8081
  project-service:
    build:
      dockerfile: Dockerfile
      context: ./project
    image: project-service:latest
    restart: on-failure
    depends_on:
      - postgresql-db
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
      - DB_JDBC_URL=jdbc:postgresql://postgresql-db:5432/onlineide-db?user=onlineide-user&password=onlineide-db-password
    ports:
      - 8080:8080
  postgresql-db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=onlineide-db
      - POSTGRES_PASSWORD=onlineide-db-password
      - POSTGRES_USER=onlineide-user
    ports:
      - 5432:5432

